# Generated by Django 4.1.2 on 2022-12-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_playlist_song_playlistuser_delete_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaylistUser',
            new_name='playlist_user',
        ),
    ]
